# Generated by Django 4.0.4 on 2022-05-22 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BaseModel', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BaseModel.basemodel')),
                ('class_name', models.CharField(default='Rookie', max_length=50, verbose_name='class')),
                ('experience', models.BigIntegerField(default=0, verbose_name='experince')),
                ('level', models.IntegerField(default=1, verbose_name='level')),
                ('attributes', models.JSONField(default=dict, verbose_name='attributes')),
                ('skills', models.JSONField(default=dict, verbose_name='skills')),
                ('achievements', models.JSONField(default=dict, verbose_name='achievements')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='params', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            bases=('BaseModel.basemodel',),
        ),
    ]
